### ISSUE TITLE
Does not compile on Debian kFreebsd

### ISSUE THREAD

**Issue by jepler** [bsdphk/Ntimed#5]
Debian kFreeBSD is an oddball, in that it has GNU make as /usr/bin/make, but your configure script detects bsd-style make.

~~~~
$ sh configure
Found bsd.prog.mk, will use it.
Makefile generated, remeber to run 'make depend'
$ make
Makefile:24: *** missing separator.  Stop.
~~~~

Unfortunately, while my system has `freebsd-make`, that's broken too :(

~~~~
$ freebsd-make depend
rm -f .depend
mkdep -f .depend -a     combine_delta.c ...
mkdep: No such file or directory
*** Error code 1
~~~~

(mkdep is installed as freebsd-mkdep but the .mk files haven't been modified to reflect this.  doh)

I would be happy to produce a patch to fix this, but I'm not sure what you would like in your philosophy of configure and build system.

The first idea that comes to mind is to check whether "make" (the one on $PATH) is a gnu-style make (the simplest test probably being make -v | grep -q GNU) rather than for the presence of bsd.mk in a standard location.

Another idea would be to generate both BSDMakefile as a BSD-format Makefile and GNUMakefile as a GNU-format Makefile (the debian manpage for freebsd-make says BSDMakefile is read in preference to Makefile/makefile, though I didn't do any checking for the universality of this)

If you let me know what approach you'd like to resolve this problem, I'll be happy to code and test it and prepare a pull request.

**Comment by bsdphk** [comment]
I added a test for GNU make, let me know if more is needed.

**Comment by jepler** [comment]
Working for me, thank you.
